#ifndef STYLE_HPP
#define STYLE_HPP
#include <QString>

const QString STYLE = "QMainWindow {"
                      "	background-color:#151a1e;"
                      "}"
                      "QPushButton{"
                      "	border-style: solid;"
                      "	border-color: #050a0e;"
                      "	border-width: 1px;"
                      "	border-radius: 5px;"
                      "	color: #d3dae3;"
                      "	padding: 2px;"
                      "	background-color: #151a1e;"
                      "}"
                      "QPushButton::default{"
                      "	border-style: solid;"
                      "	border-color: #050a0e;"
                      "	border-width: 1px;"
                      "	border-radius: 5px;"
                      "	color: #FFFFFF;"
                      "	padding: 2px;"
                      "	background-color: #151a1e;;"
                      "}"
                      "QPushButton:hover{"
                      "	border-style: solid;"
                      "	border-color: #050a0e;"
                      "	border-width: 1px;"
                      "	border-radius: 5px;"
                      "	color: #d3dae3;"
                      "	padding: 2px;"
                      "	background-color: #1c1f1f;"
                      "}"
                      "QPushButton:pressed{"
                      "	border-style: solid;"
                      "	border-color: #050a0e;"
                      "	border-width: 1px;"
                      "	border-radius: 5px;"
                      "	color: #d3dae3;"
                      "	padding: 2px;"
                      "	background-color: #2c2f2f;"
                      "}"
                      "QLineEdit {"
                      "	border-width: 1px;"
                      "	border-style: solid;"
                      "	border-color: #4fa08b;"
                      "	background-color: #222b2e;"
                      "	color: #d3dae3;"
                      "}"
                      "QLabel {"
                      "	color: #d3dae3;"
                      "}"
                      "QProgressBar {"
                      "	text-align: center;"
                      "	color: #d3dae3;"
                      "	border-radius: 10px;"
                      "	border-color: transparent;"
                      "	border-style: solid;"
                      "	background-color: #52595d;"
                      "}"
                      "QProgressBar::chunk {"
                      "	background-color: #214037	;"
                      "	border-radius: 10px;"
                      "}"
                      "QMenuBar {"
                      "	background-color: #151a1e;"
                      "}"
                      "QMenuBar::item {"
                      "	color: #d3dae3;"
                      "  	spacing: 3px;"
                      "  	padding: 1px 4px;"
                      "	background-color: #151a1e;"
                      "}"
                      "QMenuBar::item:selected {"
                      "  	background-color: #252a2e;"
                      "	color: #FFFFFF;"
                      "}"
                      "QMenu {"
                      "	background-color: #151a1e;"
                      "}"
                      "QMenu::item:selected {"
                      "	background-color: #252a2e;"
                      "	color: #FFFFFF;"
                      "}"
                      "QMenu::item {"
                      "	color: #d3dae3;"
                      "	background-color: #151a1e;"
                      "}";

#endif // STYLE_HPP